{{/*
MIT License

(C) Copyright 2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    name: nexus
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    name: operators
    {{- include "cray-drydock.labels" . | nindent 4 }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: operators
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"

---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    name: services
    {{- include "cray-drydock.labels" . | nindent 4 }}
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: services
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: user
  name: user
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: uas
    istio-injection: enabled
  name: uas
---
apiVersion: v1
kind: Namespace
metadata:
  name: spire
  labels:
    name: spire
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  labels:
    name: gatekeeper-system
    admission.gatekeeper.sh/ignore: no-self-managing
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pki-operator
  labels:
    name: pki-operator
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: pki-operator
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: vault
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    name: kyverno
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: kyverno
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenants
  labels:
    name: tenants
    {{- include "cray-drydock.labels" . | nindent 4 }}
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: tenants
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hnc-system
  labels:
    name: hnc-system
    {{- include "cray-drydock.labels" . | nindent 4 }}
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: hnc-system
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    name: argo
    istio-injection: enabled
