{{- /*
Copyright 2020, 2021 Hewlett Packard Enterprise Development LP
*/ -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sonar-jobs-watcher
  namespace: services
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: sonar-jobs-watcher
  template:
    metadata:
      labels:
        name: sonar-jobs-watcher
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: sonar
      terminationGracePeriodSeconds: 0
      containers:
      - name: "sonar"
        image: "{{ include "cray-drydock.image-prefix" .Values }}{{ .Values.sonar.jobsWatcher.image.repository }}:{{ include "cray-drydock.watcher-tag" . }}"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SCRIPT_VERSION
          value: "1"
        command:
        - "/bin/sonar-jobs-watcher.sh"
        {{- range .Values.sonar.jobsWatcher.namespaces }}
        - {{ . | quote }}
        {{- end }}
        {{- if .Values.sonar.jobsWatcher.resources }}
        {{- with .Values.sonar.jobsWatcher.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end -}}
        {{- end }}
        volumeMounts:
          - name: sonar-scripts
            mountPath: /bin/sonar-jobs-watcher.sh
            readOnly: true
            subPath: sonar-jobs-watcher.sh
          - mountPath: /etc/crictl.yaml
            name: crictl-config
            readOnly: true
          - mountPath: /run/containerd/containerd.sock
            name: crictl-sock
      volumes:
        - name: sonar-scripts
          configMap:
            defaultMode: 0700
            name: sonar
        - name: crictl-config
          hostPath:
            path: /etc/crictl.yaml
            type: File
        - name: crictl-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
