{{- /*
Copyright 2020 Hewlett Packard Enterprise Development LP
*/ -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sonar-sync
  namespace: services
  labels:
    {{- include "cray-drydock.labels" . | nindent 4 }}
spec:
  {{ with .Values.sonar.sync.schedule -}}
    schedule: "{{.minute}} {{.hour}} {{.day_of_month}} {{.month}} {{.day_of_week}}"
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cronjob-name: sonar-sync
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          serviceAccountName: sonar
          containers:
            - name: "sonar"
              image: "{{ include "cray-drydock.image-prefix" .Values }}{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
              command: ["/bin/sonar-sync.sh"]
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "2"
                limits:
                  memory: "2Gi"
                  cpu: "6"
              volumeMounts:
                - name: sonar-scripts
                  mountPath: /bin/sonar-sync.sh
                  readOnly: true
                  subPath: sonar-sync.sh
          volumes:
            - name: sonar-scripts
              configMap:
                defaultMode: 0700
                name: sonar
