# Default values for cray-drydock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.15

sonar:
  jobsWatcher:
    image:
      repository: artifactory.algol60.net/csm-docker/stable/cray-sonar
      # tag defaults to chart appVersion
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "160Mi"
        cpu: "500m"
      limits:
        memory: "320Mi"
        cpu: "8"
    namespaces:
    - services
    - nexus
    - spire
    - vault
  sync:
    schedule:
      minute: "*/1"
      hour: "*"
      day_of_month: "*"
      month: "*"
      day_of_week: "*"
