# Default values for cray-drydock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imagesHost: "dtr.dev.cray.com"

kubectl:
  image:
    repository: loftsman/loftsman
    tag: 0.5.1

sonar:
  jobsWatcher:
    image:
      repository: cray/cray-sonar
      # tag: latest
    resources:
      requests:
        memory: "160Mi"
        cpu: "500m"
      limits:
        memory: "320Mi"
        cpu: "8"
    namespaces:
    - services
    - nexus
    - spire
    - vault
  sync:
    schedule:
      minute: "*/1"
      hour: "*"
      day_of_month: "*"
      month: "*"
      day_of_week: "*"
